import 'package:flutter/material.dart';

List<IconData> appIcons = [
  Icons.accessible_forward,
  Icons.agriculture,
  Icons.ac_unit,
  Icons.access_alarm,
  Icons.accessibility_new,
  Icons.account_circle,
  Icons.adb,
  Icons.add_box,
  Icons.add_box_outlined,
  Icons.add_circle,
  Icons.add_circle_outline,
  Icons.add_location_rounded,
  Icons.airplanemode_active,
  Icons.alarm,
  Icons.album,
  Icons.all_inclusive,
  Icons.anchor,
  Icons.android,
  Icons.apps,
  Icons.assistant_photo,
  Icons.assistant_photo_outlined,
  Icons.attach_file,
  Icons.attach_money,
  Icons.audiotrack,
  Icons.auto_awesome,
  Icons.auto_stories,
  Icons.bakery_dining_outlined,
];
