import 'package:flutter/material.dart';

List<IconData> appIcons = [
  Icons.accessible_forward,
  Icons.agriculture,
  Icons.ac_unit,
  Icons.accessibility_new,
  Icons.adb,
  Icons.add_circle,
  // Icons.add_circle_outline,
  Icons.airplanemode_active,
  Icons.all_inclusive,
  Icons.anchor,
  Icons.android,
  Icons.attach_file,
  Icons.auto_awesome,
  Icons.brightness_2,
  // Icons.brightness_2_outlined,
  Icons.brightness_7,
  // Icons.brightness_7_outlined,
  Icons.bug_report,
  Icons.build,
  // Icons.build_outlined,
  Icons.cancel,
  // Icons.cancel_outlined,
  Icons.catching_pokemon,
  Icons.celebration,
  // Icons.celebration_outlined,
  Icons.check_box,
  // Icons.check_box_outlined,
  Icons.check_circle,
  // Icons.check_circle_outlined,
  Icons.child_care,
  Icons.child_friendly,
  Icons.circle,
  // Icons.circle_outlined,
  Icons.clear,
  Icons.cloud,
  // Icons.cloud_outlined,
  Icons.coffee,
  // Icons.coffee_outlined,
  Icons.color_lens,
  // Icons.color_lens_outlined,
  Icons.coronavirus,
  // Icons.coronavirus_outlined,
  Icons.directions_bike,
  Icons.directions_boat,
  Icons.directions_bus,
  Icons.directions_car,
  Icons.directions_run,
  Icons.directions_walk,
  Icons.disabled_by_default,
  // Icons.disabled_by_default_outlined,
  Icons.do_disturb,
  Icons.do_disturb_on,
  // Icons.do_disturb_on_outlined,
  Icons.downhill_skiing,
  Icons.eco,
  // Icons.eco_outlined,
  Icons.elderly,
  Icons.electric_bike,
  Icons.emoji_emotions,
  // Icons.emoji_emotions_outlined,
  Icons.emoji_events,
  // Icons.emoji_events_outlined,
  Icons.emoji_objects,
  // Icons.emoji_objects_outlined,
  Icons.extension,
  // Icons.extension_outlined,
  Icons.face,
  Icons.favorite,
  // Icons.favorite_border,
  Icons.filter_vintage,
  // Icons.filter_vintage_outlined,
  Icons.flag,
  Icons.flag_outlined,
  Icons.flare,
  Icons.flash_on,
  Icons.gamepad,
  Icons.grass,
  Icons.hail,
  Icons.hardware,
  Icons.headphones,
  Icons.healing,
  Icons.hiking,
  Icons.ice_skating,
  // Icons.ice_skating_outlined,
  Icons.kayaking,
  Icons.language,
  Icons.light_mode,
  // Icons.light_mode_outlined,
  Icons.local_fire_department,
  Icons.local_florist,
  // Icons.local_florist_outlined,
  Icons.local_pizza,
  // Icons.local_pizza_outlined,
  Icons.monetization_on,
  // Icons.monetization_on_outlined,
  Icons.mood_bad,
  Icons.moped,
  Icons.motorcycle,
  Icons.music_note,
  Icons.outlet,
  Icons.outlet_outlined,
  Icons.palette,
  // Icons.palette_outlined,
  Icons.pan_tool,
  Icons.paragliding,
  Icons.park,
  // Icons.park_outlined,
  Icons.pedal_bike,
  Icons.pest_control_rodent,
  // Icons.pest_control_rodent_outlined,
  Icons.pets,
  Icons.push_pin,
  // Icons.push_pin_outlined,
  Icons.school,
  // Icons.school_outlined,
  Icons.skateboarding,
  Icons.sledding,
  Icons.snowboarding,
  Icons.snowmobile,
  Icons.snowshoeing,
  // Icons.sports_baseball,
  Icons.sports_baseball_outlined,
  // Icons.sports_basketball,
  Icons.sports_basketball_outlined,
  Icons.sports_cricket,
  // Icons.sports_cricket_outlined,
  Icons.sports_esports,
  // Icons.sports_esports_outlined,
  // Icons.sports_football,
  Icons.sports_football_outlined,
  Icons.sports_golf,
  Icons.sports_handball,
  Icons.sports_hockey,
  Icons.sports_kabaddi,
  Icons.sports_mma,
  Icons.sports_motorsports,
  // Icons.sports_motorsports_outlined,
  Icons.sports_rugby,
  // Icons.sports_rugby_outlined,
  Icons.sports_score,
  Icons.sports_soccer,
  Icons.sports_tennis,
  // Icons.sports_volleyball,
  Icons.sports_volleyball_outlined,
  Icons.star,
  // Icons.star_border,
  Icons.storm,
  Icons.surfing,
  Icons.toys,
  // Icons.toys_outlined,
];
